### ISSUE TITLE
No unique class for BS4 blocks?

### ISSUE THREAD

**Issue by Moikapy** [kaoz70/grapesjs-blocks-bootstrap4#10]
Adopted the GJS Bootstrap 4 plugin and noticed that the elements aren't dropped into the canvas with a Class unlesss it's predefined. The Container seems to have no problems using the cid provided by grapesjs, but elements like the Header and Paragraph section are lacking the use of the cid generated by grapesjs.

Ex of container: ![container-with-class](https://user-images.githubusercontent.com/18318332/42592506-bdab2464-8517-11e8-8167-89a2a38b06f0.JPG)

Ex of Header without Dynamic Class: ![header-without-class](https://user-images.githubusercontent.com/18318332/42592589-f5812bf4-8517-11e8-935b-8f37b22b8bc3.JPG)

**Comment by kaoz70** [comment]
Hello, is this still an issue? There have been many changes and upgrades, including GrapesJS, so this might have been fixed, I cant seem to reproduce this.

**Comment by kaoz70** [comment]
I'm closing this issue for now.
