### ISSUE TITLE
Extra large device max-width breaking decorations

### ISSUE THREAD

**Issue by cluppi** [kaoz70/grapesjs-blocks-bootstrap4#14]
**Description:**
When applying certain decorations (e.g. background color) to an element that contains a Bootstrap class, an invalid media query wraps the style added causing browsers to ignore the style.

**How to reproduce issue:**
1. Start with empty canvas 
2. Click on `Body`
3. Go to `Style Manager` tab
4. Add Bootstrap class (e.g. `jumbotron`)
5. Try changing background color under `Decorations`

Result:
```
@media (max-width: 100%){
  .jumbotron{
    background-color:#d02121;
  }
}
```

The default device (`Extra Large`) shouldn't have `@media` queries for its styles and is causing browsers to ignore everything underneath it.
The `max-width` parameter should be omitted when initializing a list of devices in `devices.js`. I'll be submitting quick a PR for that.

**Comment by kaoz70** [comment]
Hey! Sorry for the late response. I merged this PR, thanks for the help!
