### ISSUE TITLE
Impossible to insert row inside container

### ISSUE THREAD

**Issue by m-0rph3us** [kaoz70/grapesjs-blocks-bootstrap4#20]
I can't  figure out how to properly insert a row inside container, maybe because the height is 0 when container is empty.
And the same apply with columns.

![bug-report-grapesjs-bootstrap4](https://user-images.githubusercontent.com/25625522/65469132-8b809100-de66-11e9-9b41-d8c768a6ca0d.gif)

**Comment by cartifon** [comment]
I'm not sure what I did, but just stopping and rerunning the project, it fixed for me...

**Comment by kaoz70** [comment]
Seems that the issue is solved, I checked and was not able to reproduce this, feel free to open this if it happens again.

**Comment by handhikadj** [comment]
@kaoz70 the container/row doesn't have height if the View Component button is off. it's like not in the canvas when it's off. this is a bug to me.
![ezgif-3-25cbbd94e0](https://user-images.githubusercontent.com/22522638/216986592-edf1f7ec-3cbb-4e45-a579-8717ac1cf195.gif)
