### ISSUE TITLE
There is a warning for deprecated method

### ISSUE THREAD

**Issue by cartifon** [kaoz70/grapesjs-blocks-bootstrap4#24]
You can see the warning when change the trait on Tab panel `Is Active`.

`grapes.min.js:2 The event 'change:selectedComponent' is deprecated, replace it with 'component:toggled' `

**Comment by kaoz70** [comment]
I saw your PR, thanks for the fix, could you fix the merge issue so that I can close this?

**Comment by kaoz70** [comment]
PR #25 should fix this issue. Closing it.
