### ISSUE TITLE
Background images do not work at all.

### ISSUE THREAD

**Issue by teamfunnels** [kaoz70/grapesjs-blocks-bootstrap4#26]
I cannot see any background images in the style manager and if I set one it does not show up in the canvas.

**Comment by kaoz70** [comment]
Background images are not specific to this plugin, maybe you should check GrapeJS docs for this. Or is there something I am missing? Could you please elaborate on what you are trying to accomplish with Bootstrap 4 and GrapesJS with background images?

**Comment by kaoz70** [comment]
I'm closing this issue, if you think that the background error if caused by this plugin feel free to reopen it again.
