### ISSUE TITLE
 c is not defined in grapesjs-blocks-bootstrap4.min.js

### ISSUE THREAD

**Issue by robertraf** [kaoz70/grapesjs-blocks-bootstrap4#27]
![Screen Shot 2020-03-05 at 8 20 38 AM](https://user-images.githubusercontent.com/33938510/75990616-c9c0b880-5eba-11ea-9f25-3fba21d51c32.png)

**Comment by lrrhero2008** [comment]
https://github.com/kaoz70/grapesjs-blocks-bootstrap4/blob/master/src/components.js#L213
`InputGroupBlock(bm, c.labels)`

And fix in grapesjs-my-plugin/grapesjs-blocks-bootstrap4/src/components/InputGroup.js
`label.form_group_input` 
`label.input_group`

**Comment by mfreeman-xtivia** [comment]
Seeing this issue as well. Happens if you simply git clone the repo and then try to bring up the index.html file in a browser. Bad bug

**Comment by bleedweedsuz** [comment]
I got the same error,
steps
1. clone
2. as per the instruction i install depen
3. npm start ----// error occur
 after this i build this project with different version
same error
![Capture](https://user-images.githubusercontent.com/10117919/77777060-142af480-7077-11ea-8a8e-43a5f762deed.PNG)

any solution??

**Comment by mfreeman-xtivia** [comment]
I would soooooooooooooo LOVE to use this plugin for a work project but thats impossible with this bug which happens every time. Does anybody have any idea how one would go about fixing this?

I would be happy to do the PR submission work if anyone knows what the fix is ...

**Comment by bleedweedsuz** [comment]
I recommended not to use this project (plugin: too many bugs) however injecting the css and js file would help to use bootstrap4 plugin in grapejs library. After that we can make custom bootstrap template using Blockmanger.

example:
````
canvas: {
       styles: [
          'https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css'
        ],
        scripts: [
          'https://code.jquery.com/jquery-3.3.1.slim.min.js',
          'https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js',
          'https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js'
        ],
````

**Comment by tmtung144** [comment]
I think an individual who has developed such a relatively good plugin, everyone can support and join hands to fix the error, then it is perfect. Sorry about my vocabulary!

**Comment by hkkvo** [comment]
Is there any fix available?

**Comment by hkkvo** [comment]
> https://github.com/kaoz70/grapesjs-blocks-bootstrap4/blob/master/src/components.js#L213
> `InputGroupBlock(bm, c.labels)`
> 
> And fix in grapesjs-my-plugin/grapesjs-blocks-bootstrap4/src/components/InputGroup.js
> `label.form_group_input`
> `label.input_group`


Is this the fix? can you please elaborate on this.

**Comment by hkkvo** [comment]
Below version is working

https://github.com/kaoz70/grapesjs-blocks-bootstrap4/tree/e2f8fc46bdc053a016a335e53a1beaba8c4f6d85

**Comment by kaoz70** [comment]
Hello, sorry for the late reply, yes I know this is kind of buggy, if anyone could help make this project better that would be great! Any good PRs are welcome.

That aside, I am using this on some production sites so this error is weird, I haven't seen this, It may be some GitHub security automatic NPM package upgrades that caused this, let me take a look.

**Comment by kaoz70** [comment]
Ok, can you please check if version 0.1.21 fixes this issue?

**Comment by mfreeman-xtivia** [comment]
Just tested with 0.1.22 and the issue does indeed seem to be fixed for me.

**Comment by kaoz70** [comment]
Great to hear that! I will close the issue then.
