### ISSUE TITLE
Unable to add space in button text

### ISSUE THREAD

**Issue by shellprog** [kaoz70/grapesjs-blocks-bootstrap4#29]
I am unable to add space in the button text, tried to edit the source files but no luck, help is appreciated.

**Comment by shellprog** [comment]
If the text is wrapped in a span then it works fine.

**Comment by kaoz70** [comment]
Can you add an example of what you are trying to acomplish?

**Comment by shellprog** [comment]
I have just dragged a button and double clicked it to change the text but it is not accepting space with spacebar

**Comment by kaoz70** [comment]
Ok, I see what you mean, let me check it out

**Comment by kaoz70** [comment]
So, I checked how the original GrapesJS form plugin handles buttons and replicated the functionality, you wont be able to double click to change the text but you have the option in the traits now

![image](https://user-images.githubusercontent.com/79406/83706620-94248c00-a5dd-11ea-9592-af59c40c22a0.png)

**Comment by shellprog** [comment]
For the time being I have created custom component and wrapped the button text in a span which is allowing to edit the text inside it with double click. Something like <button><span>Button</span></button>

**Comment by kaoz70** [comment]
Ok, I will close this issue then, If you would like to create a PR with your changes to the button you are welcome, so that we can change the button's text with double click and in the settings.
