### ISSUE TITLE
row{ display: table}

### ISSUE THREAD

**Issue by Filoz** [kaoz70/grapesjs-blocks-bootstrap4#30]
Hi,
Every time I add a row, grapes add this css

`.row{
  display:table;
  padding-top:10px;
  padding-right:10px;
  padding-bottom:10px;
  padding-left:10px;
  width:100%;
}`

This code makes bootstrap row not working.
Is possible to disable the auto add of row css?

thank you

**Comment by kaoz70** [comment]
Hey @Filoz let me check that out, I'm a little overloaded with work right now, so I wont be able to check it immediately.

**Comment by yucomds** [comment]
Same problem for me .. I think the` display:table; `should be` display:flex;` . Could you fix please? Thanks ;-)

**Comment by BuddhiAbeyratne** [comment]
Bumping this as its currently blocking us from a deployment

**Comment by BuddhiAbeyratne** [comment]
I've managed to trace it to the default row component coming from grapes-js unsure how to proceed @kaoz70 if you have a min and can give me a rundown on what to do I might be able to make a pr.

**Comment by kaoz70** [comment]
Hey @BuddhiAbeyratne sorry for the late reply. Can you put into detail here what you have found and what files are involved?

**Comment by BuddhiAbeyratne** [comment]
@kaoz70 its stemming from grapesJS's row styles. I think you are extending their row meaning you need to nullify their styles they are adding

**Comment by BuddhiAbeyratne** [comment]
I have an extension of around half a week to fix this. 
any other place I can reach out to you for a much more streamlined form of contact? so if you give me a few pointers I might be able to make the PR ASAP

**Comment by kaoz70** [comment]
I'm looking into this right now, but I cant find this, I'm seeing display: flex

**Comment by BuddhiAbeyratne** [comment]
Looked into my package.json
please make versions bellow 2.0 deprecated 
I'm on v2.2 and it fixed itself

**Comment by kaoz70** [comment]
@Filoz can you see if this is also your problem?

**Comment by kaoz70** [comment]
I'm closing this issue because it seems to be fixed
