### ISSUE TITLE
Problem with css attribute

### ISSUE THREAD

**Issue by martinsekeres** [kaoz70/grapesjs-blocks-bootstrap4#36]
Hi, im try to set LG-WIDTH for column but HTML code contains bug after 

`<style>* { box-sizing: border-box; } body {margin: 0;}*{box-sizing:border-box;}body{margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;}</style><div class="container"><div class="row"><div ="col-lg-8" class="col col-lg-8"></div></div></div>`

Problem is ="col-lg-8"

**Comment by kaoz70** [comment]
Hello, thanks for informing this bug, I wonder if #39 fixed this already

**Comment by kaoz70** [comment]
Could you please check if 0.2.2 fixes this?

**Comment by kaoz70** [comment]
I guess, 0.2.2 fixed this issue, I'm closing this. If this is not the case, feel free to open this issue again.
