### ISSUE TITLE
Uncaught ReferenceError: grapesjs is not defined

### ISSUE THREAD

**Issue by jcsofts** [kaoz70/grapesjs-blocks-bootstrap4#41]
get this error when I use it with webpack

`
import GrapesJS from 'grapesjs';
import pluginBootstrap4 from 'grapesjs-blocks-bootstrap4
GrapesJS.init({
...
plugins: [ pluginBootstrap4],
...
})

`

and got below error when run it 
grapesjs-blocks-bootstrap4.min.js:11 Uncaught ReferenceError: grapesjs is not defined

![image](https://user-images.githubusercontent.com/33087222/90950690-aef0f900-e486-11ea-9c1a-b53ef0396561.png)

**Comment by kaoz70** [comment]
As per the documentation, you have to install grapesjs as a peer dependency:

    npm i grapesjs --no-save

Did you do that?

**Comment by jcsofts** [comment]
yeah, I do that.

I download the source to my project and remove comment out the first line of grapesjs-blocks-bootstrap4/src/index.js
change `//import grapesjs from 'grapesjs';`
to `import grapesjs from 'grapesjs';`
then it works

**Comment by kaoz70** [comment]
Do you have any steps to repro this? It would be good to know also what versions of: OS, Node, NPM, Yarn, browser, etc.

**Comment by sircoko** [comment]
Hi!
I have a similar issue. In this case I'm working with a major grapesjs project, so I really dont want to take this plugin as a standalone  but import this plugin into the main project.  
So, I have cloned the original GrapesJS repo, then did  `npm i  grapesjs-blocks-bootstrap4` and tried to do `import pluginBootstrap4 from 'grapesjs-blocks-bootstrap4'`  but it says that cannot find grapesjs. 

I uncommented the **import grapesjs** line,  and also re-installed the grapesjs via `npm i grapesjs --no-save` (which doesnt have too much sense for me as I'm already working inside grapejs) ...

Please, I'm really lost

**Comment by kaoz70** [comment]
Ok, I see what you mean @jcsofts @sircoko , I've updated the plugin to 0.2.3, can you see if this fixes the issue.

**Comment by sircoko** [comment]
Ok I checked, reinstalled the node_modules and package lock. 

![image](https://user-images.githubusercontent.com/13989067/92965502-e6c6dd00-f443-11ea-92f8-68845e88086f.png)

It could be me doing something wrong..  
@kaoz70 would you tell me about the steps I should follow in order to embed this plugin into a grapesjs project?
Just to be suer. 
Thanks

**Comment by kaoz70** [comment]
@sircoko please check this link out for a simple implementation: https://codesandbox.io/s/sad-villani-w2w8l?file=/src/index.js

**Comment by jcsofts** [comment]
@kaoz70 thanks, the bug fixed

**Comment by kaoz70** [comment]
Great! Then I'm closing this issue.
