### ISSUE TITLE
platforma wireframes support?

### ISSUE THREAD

**Issue by mohd7469** [kaoz70/grapesjs-blocks-bootstrap4#42]
Hi @kaoz70, how can i add [platforma](https://platforma.ws/) collection of components and UI elements in this grapesJS any idea?

**Comment by kaoz70** [comment]
Hey! I checked them out and It looks like they are are a bunch of custom components, what this plugin does is use the standard Bootstrap components. I think you would be better off creating a new plugin for GrapesJS based on Plataforma + Bootstrap.

**Comment by mohd7469** [comment]
yes correct i am thinking to choose their platforma bootstrap wireframe custom HTML css based components

**Comment by kaoz70** [comment]
I'm closing this issue since you would need to create your own plugin to support Plataforma UI, and this is out of the scope of this repo.

**Comment by mohd7469** [comment]
what steps you followed to add bootstrap can you tell me? because both have same HTML css files I have their code of each component
