### ISSUE TITLE
component remove event fires on changing select options in select's trait

### ISSUE THREAD

**Issue by kumarabhishek008** [kaoz70/grapesjs-blocks-bootstrap4#43]
(component remove event fires on changing select options in select's trait) this thing is creating an issue beacuse when we are using (comps.reset(optComps);) reset function then it fires this component remove event .
please tell there is anything we can do with that whether using reset can we right our custom js for that . please reply it's urgent .
Thank you

**Comment by kaoz70** [comment]
Can you explain into detail the issue you are experiencing? Preferably with steps to reproduce this.

**Comment by kaoz70** [comment]
I'm closing this issue because no feedback has been received in a while

**Comment by kumarabhishek008** [comment]
Actually I forget to reply on this issue because I figured it out why it
was coming
