### ISSUE TITLE
Container, Row, and Column

### ISSUE THREAD

**Issue by BUILD3R-Dev** [kaoz70/grapesjs-blocks-bootstrap4#49]
When you added two columns and tried to changed the color of one of the column it changed both of columns, As per checking on the style it uses the class instead of the generated ID.

**Comment by dxmo** [comment]
@paragonitDFW I believe that's how GrapesJS works. If you want your changes to be applied to only the selected component you should go with the 'componentFirst' approach. Here's what GrapesJS docs are saying:

**Component-first styling**

By default, when you select a component in the canvas and apply styles on it, changes will be applied on its existent classes. This will result on changing of all the components with those applied classes. If you need the style to be applied only on the specific selected component you have to select componentFirst strategy in this way.

grapesjs.init({
  ...
  selectorManager: {
    componentFirst: true,
  },
})

**Comment by kaoz70** [comment]
I will close this issue since the last comment should fix the original problem.
