### ISSUE TITLE
how can i add editable blocks

### ISSUE THREAD

**Issue by zahidsoft** [kaoz70/grapesjs-blocks-bootstrap4#75]
how can I add bootstrap editable blocks, please help me I need it so much.  how can I get built-in editable blocks?

![Screenshot_2](https://user-images.githubusercontent.com/62140797/207495184-92e653fc-8c48-44dc-9113-7ab92045c95a.png)

**Comment by kaoz70** [comment]
Without more information it's hard to tell what is happening here, I will close this issue for now
