### ISSUE TITLE
Have problem with js file

### ISSUE THREAD

**Issue by bohdan-jdev0** [kaoz70/grapesjs-blocks-bootstrap4#9]
Hello z1lk!
When I try to connect this file 'grapesjs-blocks-bootstrap4.min.js' i have the error
" Uncaught SyntaxError: Unexpected token } " - can you help me with it?

**Comment by Neira13** [comment]
Hello @soxepo! I cannot reproduce your problem 🐱

**Comment by kaoz70** [comment]
I'm closing this issue because its old and not reproducible.
